# Generated by Django 5.1 on 2024-08-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0002_commentarydislike_commentarylike_dreamdislike_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="photo",
            new_name="profile_picture",
        ),
    ]
