# Generated by Django 5.1 on 2024-08-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0005_alter_user_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dream",
            name="categories",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
