# Generated by Django 5.1 on 2024-08-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0006_remove_dream_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dream",
            options={"ordering": ("-date_recorded",)},
        ),
        migrations.AlterModelOptions(
            name="emotion",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="symbol",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="emotion",
            name="recurrence_count",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="recurrence_count",
        ),
    ]
