# Generated by Django 5.1 on 2024-08-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0008_alter_commentary_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="date_recorded",
            field=models.DateTimeField(),
        ),
    ]
