# Generated by Django 5.1 on 2024-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0009_alter_dream_date_recorded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="date_recorded",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
