# Generated by Django 5.1 on 2024-08-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0010_alter_dream_date_recorded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotion",
            name="description",
            field=models.TextField(default="smt"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="commentarydislike",
            unique_together={("owner", "commentary")},
        ),
        migrations.AlterUniqueTogether(
            name="commentarylike",
            unique_together={("owner", "commentary")},
        ),
        migrations.AlterUniqueTogether(
            name="dreamdislike",
            unique_together={("owner", "dream")},
        ),
        migrations.AlterUniqueTogether(
            name="dreamlike",
            unique_together={("owner", "dream")},
        ),
    ]
