# Generated by Django 5.1 on 2024-08-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0011_emotion_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="emotion",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emotions",
                to="dream.category",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="symbols",
                to="dream.category",
            ),
        ),
    ]
