# Generated by Django 5.1 on 2024-08-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0012_category_emotion_category_symbol_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbol",
            name="category",
        ),
        migrations.RemoveField(
            model_name="emotion",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
