# Generated by Django 5.1 on 2024-09-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0013_remove_symbol_category_remove_emotion_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ("-created_time",),
                "verbose_name_plural": "Commentaries",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"ordering": ("-created_time",)},
        ),
    ]
