# Generated by Django 5.1 on 2024-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0014_alter_commentary_options_alter_follow_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(default="2000-02-12"),
            preserve_default=False,
        ),
    ]
