# Generated by Django 5.1 on 2024-09-06 11:47

from django.db import migrations, models

from users.models import validate_birth_date


class Migration(migrations.Migration):
    dependencies = [
        ("dream", "0016_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default="2004-08-11", validators=[validate_birth_date]
            ),
            preserve_default=False,
        ),
    ]
