# Generated by Django 5.1 on 2024-09-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0017_alter_user_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
